// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/signup": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/verify-email": {
    params: {};
  };
  "/api/*": {
    params: {
      "*": string;
    };
  };
  "/home": {
    params: {};
  };
  "/compose": {
    params: {};
  };
  "/settings": {
    params: {};
  };
  "/:username": {
    params: {
      "username": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/signup" | "/login" | "/verify-email" | "/api/*" | "/home" | "/compose" | "/settings" | "/:username";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/signup.tsx": {
    id: "routes/signup";
    page: "/signup";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/verify-email.tsx": {
    id: "routes/verify-email";
    page: "/verify-email";
  };
  "routes/api/$.tsx": {
    id: "routes/api/$";
    page: "/api/*";
  };
  "routes/_layout.tsx": {
    id: "routes/_layout";
    page: "/home" | "/compose" | "/settings" | "/:username";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/home";
  };
  "routes/compose.tsx": {
    id: "routes/compose";
    page: "/compose";
  };
  "routes/settings.tsx": {
    id: "routes/settings";
    page: "/settings";
  };
  "routes/$username.tsx": {
    id: "routes/$username";
    page: "/:username";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/signup": typeof import("./app/routes/signup.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/verify-email": typeof import("./app/routes/verify-email.tsx");
  "routes/api/$": typeof import("./app/routes/api/$.tsx");
  "routes/_layout": typeof import("./app/routes/_layout.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/compose": typeof import("./app/routes/compose.tsx");
  "routes/settings": typeof import("./app/routes/settings.tsx");
  "routes/$username": typeof import("./app/routes/$username.tsx");
};